name: Deploy Weather Function

on:
  push:
    branches:
    - v1.0

env:
  AZURE_FUNCTIONAPP_NAME: learning-blazor-functions
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src/Web.Functions/published
  CONFIGURATION: Release
  WORKING_DIRECTORY: src/Web.Functions

jobs:
  deploy-azure-function:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.LEARNING_BLAZOR_FUNCTIONS_FFFF }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
